stages:
    - build
    - publish
build:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    stage: build
    script:
        - dotnet build "Database/Database.csproj" -c Release
deploy:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    stage: publish
    rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    script:
        - dotnet pack -c Release
        - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
        - cd "Database/bin/Release"
        - dotnet nuget push *.nupkg --source gitlab
